In [7]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [33]:
# Initialization of tensors
x = tf.constant(4.0, shape = (1,1), dtype = tf.float32)
x = tf.constant([[1,2,3],[4,5,6]])
x = tf.ones((3,3))
x = tf.zeros((2,3))
x = tf.eye(3)
x = tf.random.normal((3,3), mean = 0, stddev = 1)
x = tf.random.uniform((1,3), minval = 0, maxval = 1)
x = tf.range(start = 1, limit =10, delta = 2)
x = tf.cast(x,dtype=tf.float64)
#tf.float (16, 32, 64), tf.int (8,16,32,64), tf.bool
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [47]:
# mathematical Operations
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x,y)
z = x + y
z = tf.subtract(x,y)
z = x - y
z = tf.divide(x, y)
z = x / y
z = tf.multiply(x, y)
z = x * y
z = tf.tensordot(x, y, axes = 1)
z = tf.reduce_sum(x*y, axis = 0)
z = x ** 5

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[-1.0790846   0.95670277  0.73848045 -0.24857454]
 [ 3.3893847   2.3274462  -1.2413924   2.2559571 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-1.0790846   0.95670277  0.73848045 -0.24857454]
 [ 3.3893847   2.3274462  -1.2413924   2.2559571 ]], shape=(2, 4), dtype=float32)


In [59]:
#indexing
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
x = tf.constant([[1,2],[3,4],[5,6]])
print(x[0,:])
print(x[:2,:])
x = tf.range(9)
print(x)
x = tf.reshape(x,(3,3))
print(x)
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
